Repository OmokNoonE/OnionHotSayYo-backend, pull requests merged in 2024-04, with the labels that each got.

#26 [PR] 회원관리 기능 개발
  OnionHotSayYo/build.gradle
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/OnionHotSayYoApplication.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/aggregate/Auth.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/aggregate/Member.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/aggregate/Nationality.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/controller/AuthController.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/controller/MemberController.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/dto/AuthDTO.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/dto/MemberDTO.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/repository/AuthRepository.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/repository/MemberRepository.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/repository/NationalityRepository.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/security/AuthenticationFilter.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/security/JwtFilter.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/security/JwtTokenProvider.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/security/JwtUtil.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/security/WebSecurity.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/service/AuthService.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/service/AuthServiceImpl.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/service/MemberService.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/service/MemberServiceImpl.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/vo/RequestLogin.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/vo/RequestMember.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/vo/ResponseMember.java
Labels: feature

#38 [PR] 알림 기능 개발 (SSE Emitter)
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/notification/command/aggregate/Notification.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/notification/command/controller/NotificationController.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/notification/command/dto/NotificationDTO.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/notification/command/repository/EmitterRepository.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/notification/command/repository/EmitterRepositoryImpl.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/notification/command/repository/NotificationRepository.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/notification/command/service/NotificationService.java
Labels: feature

#36 [PR] 국적 관련 기능 개발
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/aggregate/Member.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/aggregate/Nationality.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/service/MemberServiceImpl.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/nationality/aggregate/Nationality.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/nationality/controller/NationalityController.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/nationality/dto/NationalityDTO.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/nationality/repository/NationalityRepository.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/nationality/service/NationalityService.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/nationality/service/NationalityServiceImpl.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/nationality/vo/ResponseNationality.java
Labels: remove, feature

#37 [PR] 번역 API 기능 개발
  OnionHotSayYo/build.gradle
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/responseEntity/ResponseMessage.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/translator/aggregate/Translation.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/translator/controller/TranslationController.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/translator/dto/TranslationDTO.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/translator/repository/TranslationRepository.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/translator/service/TranslationService.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/translator/service/TranslationServiceImpl.java
  OnionHotSayYo/src/test/java/org/omoknoone/onionhotsayyo/translator/service/TranslationServiceImplTests.java
Labels: feature

#39 [PR] 팔로우 기능 개발
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/follow/command/aggregate/Follow.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/follow/command/controller/FollowController.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/follow/command/dto/FollowDTO.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/follow/command/repository/FollowRepository.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/follow/command/service/FollowService.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/follow/command/service/FollowServiceImpl.java
Labels: feature

#40 [PR] 댓글 기능 개발
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/comment/command/aggregate/Comment.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/comment/command/controller/CommentController.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/comment/command/dto/CommentCreateDTO.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/comment/command/dto/CommentDTO.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/comment/command/dto/CommentDetailDTO.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/comment/command/dto/CommentReplyDTO.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/comment/command/repository/CommentRepository.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/comment/command/service/CommentService.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/comment/command/service/CommentServiceImpl.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/reply/command/aggregate/Reply.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/reply/command/controller/ReplyController.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/reply/command/dto/ReplyDTO.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/reply/command/repository/ReplyRepository.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/reply/command/service/ReplyService.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/reply/command/service/ReplyServiceImpl.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/reply/command/vo/ReplyVO.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/reply/command/vo/RequestReply.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/reply/command/vo/ResponseReply.java
Labels: feature

#41 [PR] 북마크 기능 개발
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/bookmark/command/aggregate/Bookmark.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/bookmark/command/controller/BookmarkController.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/bookmark/command/dto/BookmarkDTO.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/bookmark/command/repository/BookmarkRepository.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/bookmark/command/service/BookmarkService.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/bookmark/command/service/BookmarkServiceImpl.java
Labels: feature

#42 [PR] 좋아요 기능 개발
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/star/command/aggregate/Star.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/star/command/controller/StarController.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/star/command/dto/StarDTO.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/star/command/repository/StarRepository.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/star/command/service/StarService.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/star/command/service/StarServiceImpl.java
Labels: feature

#43 [PR] 게시물 기능 개발
  OnionHotSayYo/build.gradle
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/exceptions/BusinessRuleViolationException.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/exceptions/GlobalExceptionHandler.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/exceptions/PostNotFoundException.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/command/aggregate/Category.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/command/aggregate/Language.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/command/aggregate/Location.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/command/aggregate/Post.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/command/controller/PostController.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/command/dto/MyPostListDTO.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/command/dto/PostFormDTO.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/command/repository/PostRepository.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/command/service/PostService.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/command/service/PostServiceImpl.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/command/service/PostServiceImpl_old.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/command/vo/PostDetailVO.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/command/vo/PostSummaryVO.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/command/vo/RequestMyPostList.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/command/vo/ResponseMyPostList.java
  OnionHotSayYo/src/main/resources/application.yml
  OnionHotSayYo/src/test/java/org/omoknoone/onionhotsayyo/post/command/service/PostServiceImplTest.java
  OnionHotSayYo/src/test/java/org/omoknoone/onionhotsayyo/post/command/service/PostServiceImplTests.java
Labels: feature

#48 [PR] 게시물 기능 개발 수정 1차
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/OnionHotSayYoApplication.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/exceptions/BusinessRuleViolationException.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/exceptions/GlobalExceptionHandler.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/aggregate/Category.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/aggregate/Language.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/aggregate/Location.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/aggregate/Post.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/command/dto/MyPostListDTO.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/command/dto/PostFormDTO.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/command/service/PostServiceImpl_old.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/command/vo/PostSummaryVO.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/command/vo/RequestMyPostList.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/command/vo/ResponseMyPostList.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/controller/PostController.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/dto/MyPostListDTO.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/dto/PostListByCategoryDTO.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/dto/WritePostDetailDTO.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/repository/PostRepository.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/service/PostService.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/service/PostServiceImpl.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/vo/ResponseMyPostList.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/vo/ResponsePostDetail.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/post/vo/ResponsePostListByCategory.java
  OnionHotSayYo/src/main/resources/application.yml
  OnionHotSayYo/src/test/java/org/omoknoone/onionhotsayyo/post/command/service/PostServiceImplTests.java
Labels: refactor, rename

#49 [PR] AOP 알림 기능 및 쪽지 기능 구현
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/comment/command/dto/CommentDTO.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/comment/command/service/CommentService.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/comment/command/service/CommentServiceImpl.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/follow/command/service/FollowServiceImpl.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/letter/command/aggregate/Letter.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/letter/command/controller/LetterController.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/letter/command/dto/LetterDTO.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/letter/command/repository/LetterRepository.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/letter/command/service/LetterService.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/letter/command/service/LetterServiceImpl.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/notification/command/controller/NotificationController.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/notification/command/service/NotificationAspect.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/notification/command/service/NotificationService.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/reply/command/service/ReplyServiceImpl.java
Labels: feature

#50 [PR] 회원가입, 로그인 클라이언트와 통신
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/config/WebConfig.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/controller/MemberController.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/security/AuthenticationFilter.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/security/CorsConfig.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/security/WebSecurity.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/member/vo/RequestSignUpMember.java
Labels: feature, refactor

#54 [PR] 알림 발송 시 URL 추가
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/follow/command/service/FollowServiceImpl.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/notification/command/service/NotificationAspect.java
  OnionHotSayYo/src/main/java/org/omoknoone/onionhotsayyo/notification/command/service/NotificationService.java
Labels: feature

#59 [PR] 로그인 시 헤더 내용 추가, 마이페이지 작성
  .gitignore
  src/main/java/org/omoknoone/onionhotsayyo/member/aggregate/Member.java
  src/main/java/org/omoknoone/onionhotsayyo/member/controller/MemberController.java
  src/main/java/org/omoknoone/onionhotsayyo/member/security/AuthenticationFilter.java
  src/main/java/org/omoknoone/onionhotsayyo/member/security/CorsConfig.java
  src/main/java/org/omoknoone/onionhotsayyo/member/security/WebSecurity.java
  src/main/java/org/omoknoone/onionhotsayyo/member/vo/ResponseMember.java
  src/main/java/org/omoknoone/onionhotsayyo/nationality/service/NationalityService.java
  src/main/java/org/omoknoone/onionhotsayyo/nationality/service/NationalityServiceImpl.java
Labels: feature
